apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-control-app
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: k8s-control-role
rules:
  - apiGroups: [ "" ] # 核心API组
    resources: [ "pods", "configmaps" ] # 在此处添加pods
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "apps" ] # apps API组
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-control-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: k8s-control-app
    namespace: default
roleRef:
  kind: Role
  name: k8s-control-role
  apiGroup: rbac.authorization.k8s.io