apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-control-app
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: k8s-control-role
rules:
  - apiGroups: ["", "apps"]
    resources: ["deployments", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-control-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: k8s-control-app
    namespace: default
roleRef:
  kind: Role
  name: k8s-control-role
  apiGroup: rbac.authorization.k8s.io